[supervisord]
nodaemon=true
user=www-data
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:artisan-serve]
command=php artisan serve --host=0.0.0.0 --port=80
directory=/app
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:artisan-queue]
command=php artisan queue:work
directory=/app
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0